name: Deploy Laravel ke InfinityFree
on:
  push:
    branches:
      - main  # Ganti ke 'master' jika itu nama branch utamamu
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Ambil Kode Terbaru
      uses: actions/checkout@v3

    - name: Sinkronisasi File via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        timeout: 60000
        local-dir: ./
        server-dir: /webabsensiperpustakaan.site.je/htdocs/
        exclude: |
          **/.git*
          **/node_modules/**
          .env
